# Generated by Django 3.2.5 on 2022-01-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordtree', '0005_word_romanized'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
