# Generated by Django 3.2.5 on 2022-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordtree', '0002_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
